baseURL = 'https://rochdamour.com/'
languageCode = 'en-ca'
title = "Roch D'amour's site"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blogs'
weight = 20

[[menus.main]]
name = 'Portfolio'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Lab Reports'
pageRef = '/homelab'
weight = 40

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 50

[markup]
  [markup.highlight]
    style = "fruity"  # You can set different styles here (e.g., github, dracula, etc.)
    lineNos = true     # Whether to show line numbers
