baseURL = 'https://notarock.lol/'
languageCode = 'en-ca'
title = "Notarock's site"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Lab Reports'
pageRef = '/homelab'
weight = 30

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 40

[markup]
  [markup.highlight]
    style = "fruity"  # You can set different styles here (e.g., github, dracula, etc.)
    lineNos = true     # Whether to show line numbers
